[package]
name = "morse_code"
version = "0.0.0"
authors = ["Damon Marc Rocha <dmarcr1997@gmail.com>", "@RandyMcMillan <randy.lee.mcmillan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
